version: "3.8"
name: e-pos

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: e-pos
        container_name: e-pos-container
        ports:
            - "8002:80"
        volumes:
            - ./build:/usr/share/nginx/html
            - ./nginx:/etc/nginx/conf.d
        restart: unless-stopped
        networks:
            - e-pos

networks:
    e-pos:
        driver: bridge
